// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX8zWhRNdnFlecvEMBP3es6xxLJ3giN9g',
    appId: '1:9095115288:web:8f6e4cc7077782a4b1096d',
    messagingSenderId: '9095115288',
    projectId: 'minimal-socil-app',
    authDomain: 'minimal-socil-app.firebaseapp.com',
    storageBucket: 'minimal-socil-app.appspot.com',
    measurementId: 'G-TYC0701PKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNoJcWZQoxuGlrZ6hr4G9VxfWNPxIse9I',
    appId: '1:9095115288:android:073dec77e9d9415bb1096d',
    messagingSenderId: '9095115288',
    projectId: 'minimal-socil-app',
    storageBucket: 'minimal-socil-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASGeqiFX1rBDWlUxnrLrDh9X9tVC8hdig',
    appId: '1:9095115288:ios:63c7620ddaeedd97b1096d',
    messagingSenderId: '9095115288',
    projectId: 'minimal-socil-app',
    storageBucket: 'minimal-socil-app.appspot.com',
    iosBundleId: 'com.example.socialMediaAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASGeqiFX1rBDWlUxnrLrDh9X9tVC8hdig',
    appId: '1:9095115288:ios:63c7620ddaeedd97b1096d',
    messagingSenderId: '9095115288',
    projectId: 'minimal-socil-app',
    storageBucket: 'minimal-socil-app.appspot.com',
    iosBundleId: 'com.example.socialMediaAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX8zWhRNdnFlecvEMBP3es6xxLJ3giN9g',
    appId: '1:9095115288:web:fe5dd91dd60f6d7cb1096d',
    messagingSenderId: '9095115288',
    projectId: 'minimal-socil-app',
    authDomain: 'minimal-socil-app.firebaseapp.com',
    storageBucket: 'minimal-socil-app.appspot.com',
    measurementId: 'G-W81XFLKKHX',
  );
}
